### ISSUE TITLE
P1: Student Management > Student Problem Creation is not saving Educ Grade

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#59] opened 2014-12-20 08:42 UTC
Go to Student Management
Select student Iman Mahmoud
Modify Student Problem
Actual: Education Grade is set to Grade 1.
Expected: It was saved as Primary.
Change it to Primary and Save the problem.
Return and you will see that it reverted back to Grade 1.

**Comment by RaymondYounan** [comment] 2015-01-24 22:26
Done
Duplicate of #164

**Comment by tannourynadine** [comment] 2015-01-28 12:48
Verified the "Education Grade" field maintain the previously selected value in Edit mode.

**Closed as completed by tannourynadine** 2015-01-28 12:48 UTC
Labels: P1, Verified
