### ISSUE TITLE
P3: Teacher > Teacher Management > Add a star next to the required fields to inform the user of the required information.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#139] opened 2015-01-13 07:45 UTC
Add a star next to the below fields:
- Position Title 
- Teacher Education Level 
- Native Language 
- Gender 
- Marital Status 
- Country

**Comment by DrJoeHage** [comment] 2015-01-18 17:41
Duplicate of #39.

**Closed as completed by DrJoeHage** 2015-01-18 17:41 UTC
Labels: Duplicate, P3, Verified
