### ISSUE TITLE
P2: Global Administration > Facility Type > The user is not able to update or delete a Facility Type

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#176] opened 2015-01-16 17:17 UTC
- The following error message is generated when the user tries to update a facility type:
  "Error updating the Facility Type:The conversion of a varchar data type to a datetime data type resulted in an out-of-range value. The statement has been terminated."
- The following error message is generated when the user tries to delete a facility type:
  "Error in deleting Facility Type:The conversion of a varchar data type to a datetime data type resulted in an out-of-range value. The statement has been terminated."

**Comment by RaymondYounan** [comment] 2015-01-16 17:59
Issue fixed
Duplicate of #174

**Comment by DrJoeHage** [comment] 2015-01-18 17:04
Verified.

**Closed as completed by DrJoeHage** 2015-01-18 17:04 UTC
Labels: P2, Verified
