### ISSUE TITLE
P2: Center Management > Unable to save New School for a country other than Iraq

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#66] opened 2014-12-22 14:13 UTC
After entering data for a new school and attempting to save the new school, the following error message is displayed:

Error in creating School: An error occurred while updating the entries. See the inner exception for details.

**Comment by RaymondYounan** [comment] 2014-12-26 18:54
Done

**Comment by tannourynadine** [comment] 2015-01-02 08:18
The user is able to create new school if it belongs to Iraq, **however** if the user selects a country different than the "Iraq", the following error message is generated:“Error getting the Governorates:undefined” and the user is not able to create the new school.

**Comment by RaymondYounan** [comment] 2015-01-24 14:34
Duplicate of #51

**Comment by RaymondYounan** [comment] 2015-01-25 20:01
Done.
As agreed we removed all countries except Iraq

**Comment by tannourynadine** [comment] 2015-01-26 10:37
Verified that no error message is generated and the user is able to create a new school, and only the Iraq is available in the “Country” drop down menu.

**Closed as completed by tannourynadine** 2015-01-26 10:37 UTC
Labels: P2, Duplicate, Verified
